### ISSUE TITLE
Provide a means to specify content in the Form Media class

### ISSUE THREAD

**Issue by jensenbox** [jazzband/django-pipeline#154]
Seems like it would be natural to add in the ability for forms to use pipeline.

https://docs.djangoproject.com/en/dev/topics/forms/media/

**Comment by chipx86** [comment]
I know this is an old request at this point, but I was recently in need of this myself for something we're working on, and have a patch in progress that was going to be internal. Interested in it?

Basically, what it allows you to do is to define a `css_packages`/`js_packages` in your form or widget's `Media` and have that convert to either the bundled file (if `PIPELINE_ENABLED` is `True`) or the list of source files (if `PIPELINE_ENABLED` is `False`). Here's an example:

```python
from django import forms
from pipeline.forms import PipelineFormMedia

...

class MyForm(forms.Form):
    ...

    class Media(PipelineFormMedia):
        css_packages = {
            'all': ('my-form-styles', 'some-widget-styles'),
        }
        js_packages = ('my-form-scripts',)
```

Behind the scenes, `PipelineFormMedia` makes use of a metaclass that adds special `css` and `js` properties to the resulting class. When accessed by Django's form media support, these will go through the same rough process that the template tags go through, making a determination of whether to reference source or output files and then going through any necessary compilation process. This means automatic support for any custom widgets or forms when used in the Django admin UI.

The one difference between this and the template tags is that we're reliant on Django's hard-coded strings for doing the `<link>` or `<script>`, instead of the templates provided by Pipeline or the caller, but I think that's a reasonable sacrifice, in this case.

Interested in a patch?

**Comment by cyberdelia** [comment]
@chipx86 I'm sure such a patch would be more than welcome :bowtie:
