### ISSUE TITLE
Ignore missing files

### ISSUE THREAD

**Issue by chrisspen** [jazzband/django-pipeline#302]
In large projects that use dozens of third-party libraries, invariably, some library will reference a `url(../../..somefile)` which doesn't exist. When running `manage.py collectstatic` with django-pipeline, this will result in an incredibly unhelpful error like:

```
ValueError: The file 'tinymce/js/tinymce/plugins/compat3x/img/icons.gif' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x1ca6750>.
```

Not only does pipeline not mention which file attempts to include this file, searching for `img/icons.gif` myself results in 42 matches. Even if I could locate the issue, I can't easily fix the missing file, since it's a third-party library. This means pipeline is effectively blocking all my deployments because of a missing file I don't even use.

Ideally, pipeline should report which resource is referencing a missing file and allow specifying an option to ignore it. This is very similar to the `https://github.com/adamcharnock/django-pipeline-forgiving` fork, although I think this would be a good idea for the main branch.

**Comment by karolyi** [comment]
@cyberdelia, can we have warnings instead of errors on compilation? As you can see, I'm bumping into more and more error because of this, and we can't expect every one of them corrected, so I have to introduce more and more `-i` flags with comments that they should be removed when those bugs get fixed.

The problem is, since I can't specify paths explicitly (`-i` only accepts filenames without paths), sooner or later we will run into problems when having a complex project with many packages having overlapping (and needed) filenames.

**Comment by karolyi** [comment]
yeah, on a side note, some people like @eonasdan are even unwilling to resolve the problem, against my best intentions. he just deleted the issue I created and banned me in his repo, after making a phlegmatic comment. what a dick move.

so because of this, the problem here won't be solved on his behalf, since he is unwilling to help.

**Comment by Eonasdan** [comment]
actually @karolyi I disabled **all** the issues. I don't have time to work on the picker at the moment.

"No is a complete sentence".

Guess you'll have to get over yourself

**Comment by yairchu** [comment]
We're using "slider revolution" which has this line in a css:

    .tp-bannertimer { visibility: hidden; width:100%; height:5px; /*background:url(../assets/timer.png);*/ background: #fff; background: rgba(0,0,0,0.15); position:absolute; z-index:200; top:0px}

It seems to reference `../asserts/timer.png` (which doesn't exist) but it's actually just in a comment, not a real reference.

This also triggers this problem. In our case we've removed the comment to work around this and then everything worked fine..

**Comment by czue** [comment]
Had this same issue using lodash and (via dependency) firebug-lite. The error I was getting was

```
ValueError: The file 'lodash/vendor/firebug-lite/skin/xp/condBorders.png' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7fd3ed9b9ad0>.
```

And the solution as mentioned above is to run:

```
./manage.py collectstatic --ignore=firebug-lite
```

**Comment by diegueus9** [comment]
I just had the same issue with jquery-compiler, as @czue suggested, the flag `--ignore` did the trick
```
./manage.py collectstatic --no-input -c -v 3 --ignore=jquery-confirm
```

However, it would be nice to have this issue fixed
