### ISSUE TITLE
PipelineCachedStorage requires both versioned & non-versioned static files

### ISSUE THREAD

**Issue by bitcity** [jazzband/django-pipeline#462]
I'm using `PipelineCachedStorage` to use css/jss assets with version numbers in their names (the md5 sum). After running collectstatic, if I remove the 'non-versioned' assets, I get an error about missing css/js files. 

    ValueError: The file could not be found with <pipeline.storage.PipelineCachedStorage.

This goes away when I copy back the non-versioned assets to static root. The source of the served HTML page also shows that it uses versioned static files. What's the need for the non-versioned ones?

**Comment by AlexHill** [comment]
This is expected. In your templates, you have for example ``{% static "css/style.css" %}`` – the original file still needs to be there to calculate the MD5 sum and work out the file name. The MD5 sum is cached, but still needs to be calculated at least once!

**Comment by bitcity** [comment]
Versioned & non-versioned files have the exact same content. The difference is only in the file name. E.g. if non-versioned file is called `jquery-10.js`, the versioned counterpart would be of the form `jquery-10.[a-z0-9]{12}.js`. Since one can be derived from other without much effort, what's the need to have the file?

**Comment by AlexHill** [comment]
When your templates are evaluated, the ``static`` tag needs some way to work out the versioned file name from the raw file name, in order to put the versioned file name in your output.

Django's ``CachedStaticFilesStorage`` does this by hashing the original file again. It can't just take any old file matching the pattern, because multiple versioned files can be present at the same time – that's one of the reasons versioned files are used in the first place.

(BTW the content isn't always the same – for example, references to other static files in CSS rules are replaced by references to their versioned counterparts.)

Django also has a [ManifestStaticFilesStorage backend](https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#manifeststaticfilesstorage) which stores filename mappings in a JSON file during ``collectstatic`` instead of recalculating and caching them at runtime. I don't think Pipeline supports that yet but looking at the code, it wouldn't be hard to implement.
