### ISSUE TITLE
Do there any blockers to bump new release?

### ISSUE THREAD

**Issue by jramnai** [jazzband/django-pipeline#752]
We are looking forward to using `django-pipeline` with Django 3.2 on [edX](https://github.com/edx).

Required PR - #751 is already merged into the master branch.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by jezdez** [comment]
Seems like updating the `HISTORY.rst` would be useful by going through the commits that have been added since that least release. I also see that 2.0.6 wasn't added to it. Then maybe open a PR and see if a [project lead](https://jazzband.co/projects/django-pipeline) can do the release?

BTW, since edX is relying on it, why not sponsor the work on django-pipeline or become a [django-pipeline team member](https://jazzband.co/projects/django-pipeline) and help out more often?

**Comment by jezdez** [comment]
Since the document (written by @jmbowman) doesn't mention this at all, I just want to clarify that Jazzband is a fiscal sponsoree of the Python Software Foundation nowadays, which means edX can donate to Jazzband via https://jazzband.co/donate.

Generally speaking I would appreciate if you would adopt *funding* Open Source software you're relying on to your list of preferences in ["Handling Outdated Dependencies"](https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies). Lack of funding (read: time) is often the cause of OSS projects being "outdated" after all.

**Comment by jmbowman** [comment]
We would very much like to do so, but it's been a hard pitch at a nonprofit with a pretty tight budget.  If the [2U acquisition of edX](https://www.transformingdigitaleducation.com/) goes through as planned, my hope is that we'll start to have a budget for helping support our dependencies financially instead of just code contributions.  And I'll be giving a [talk at DjangoCon](https://2021.djangocon.us/talks/herding-ponies-coordinating-and-django/) presenting all the tooling and processes we've developed around Django upgrades, all open source, in hopes of making it available and ever more useful for other Django package maintainers to reduce the workload involved in such updates.

**Comment by jezdez** [comment]
> We would very much like to do so, but it's been a hard pitch at a nonprofit with a pretty tight budget. If the [2U acquisition of edX](https://www.transformingdigitaleducation.com/) goes through as planned, my hope is that we'll start to have a budget for helping support our dependencies financially instead of just code contributions. And I'll be giving a [talk at DjangoCon](https://2021.djangocon.us/talks/herding-ponies-coordinating-and-django/) presenting all the tooling and processes we've developed around Django upgrades, all open source, in hopes of making it available and ever more useful for other Django package maintainers to reduce the workload involved in such updates.

Nice, glad you're talking about this, I'm sure many have similar problems to solve. Crossing my fingers all goes okay with the acquisition!

**Comment by cyberdelia** [comment]
[](url)
