### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by peymanslh** [jazzband/django-pipeline#788]
Recently we added support for the TypeScript compiler, dropped support for the manifesto, and officially added support for Python 3.11 and Django 4.1. Based on these changes we can release Django pipeline 2.1.0.

@cyberdelia 
Also, I wanted to ask you if you agree maybe I could ask to lead the project to help with releasing and maintaining the project.

**Comment by cyberdelia** [comment]
I made a roadie ticket, in the meantime if you release a new version, I’ll get an approval email and the package will get released.

**Comment by peymanslh** [comment]
Thanks, I sent PR for changes on `history.rst`.
Then I push the `2.1.0` tag.

**Comment by DUPLESSIS46** [comment]
What do you think of Hygraph?

When writing your review, please include as much detail as possible about your experience with the product, as well as information about yourself, so that we can verify your identity. Please make sure your review is written in English. Reviews about your own product, or a competitors product, will not be published. View Review Guidelines.

Any information you provide on this page will be treated in accordance with our privacy policy. Your responses within the below will be available to others as publicly facing reviews describing your experience with the product. We will email the provided email address to verify your identity, communicate with you about this review, and potentially invite you to join our review program, as outlined within our Review Guidelines. By providing this information, you are consenting to these uses.
